//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace usmanNorbit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class custComplaint
    {
        public int Id { get; set; }
        public string message { get; set; }
        public string email { get; set; }
        public string name { get; set; }
        public byte status { get; set; }
        public System.DateTime date { get; set; }
        public string subject { get; set; }
    }
}
